name: 定时任务

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 执行程序
      run: |
        pip install requests
        python3 job.py
